import {
  FaGithub,
  FaLinkedin,
  FaInstagram,
  FaDiscord,
  FaPhone,
  FaEnvelope,
  FaLocationDot,
  FaFilePdf,
  FaServer,
  FaJava,
  FaMobileScreen,
  FaLaptopCode,
  FaTrophy,
  FaCode,
  FaGraduationCap,
} from 'react-icons/fa6';
import { FaXTwitter } from 'react-icons/fa6';
import { VscVscode as SiVisualstudiocode } from 'react-icons/vsc';
import {
  SiReact,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiCplusplus,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiPostman,
  SiVercel,
  SiNetlify,
  SiFirebase,
  SiFigma,
  SiFramer,
  SiLeetcode,
  SiCodechef,
  SiCodeforces,
  SiGeeksforgeeks,
} from 'react-icons/si';

const iconMap = {
  FaGithub,
  FaLinkedin,
  FaInstagram,
  FaXTwitter,
  FaDiscord,
  FaPhone,
  FaEnvelope,
  FaLocationDot,
  FaFilePdf,
  FaServer,
  FaJava,
  FaMobileScreen,
  FaLaptopCode,
  FaTrophy,
  FaCode,
  FaGraduationCap,
  SiReact,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiCplusplus,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiVisualstudiocode,
  SiPostman,
  SiVercel,
  SiNetlify,
  SiFirebase,
  SiFigma,
  SiFramer,
  SiLeetcode,
  SiCodechef,
  SiCodeforces,
  SiGeeksforgeeks,
};

export const getIcon = (name, className = '') => {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className={className} aria-hidden="true" />;
};
